### ISSUE TITLE
Support for virtualbox 7.1

### ISSUE THREAD

**Issue by inwoker** [svpernova09/homestead#8]
Virtualbox 7.1 is out. Can you please add support for it for windows? Also there is a mac version of Virtualbox 7.1 for Apple Silicon. Can you support it instead of Parallels Desktop? Or just support Virtualbox for mac together with Parralels Desktop? Parallels Desktop is paid and kinda expensive. You need Business version to use it, right?

**Comment by ALameLlama** [comment]
Vagrant itself doesn't support Virtualbox 7.1 as of right now https://github.com/hashicorp/vagrant/issues/13501

For the support for VirtualBox on arm. new boxes would need to be published to support these so that's up to Joe if he will do that.

**Comment by inwoker** [comment]
@svpernova09 
Thank you Joe. Will there be support for virtualbox on mac m1?

**Comment by svpernova09** [comment]
> @svpernova09 Thank you Joe. Will there be support for virtualbox on mac m1? Maybe you need any help with that?

There already is. In fact, [Svpernova09/homestead](https://github.com/svpernova09/homestead/) has already released a base box that's newer than laravel/homestead (it also features PHP 8.4 RC). The only thing that needs to be added at the moment is libvirt.

**Comment by inwoker** [comment]
Wow, many thanks. I missed it somehow

**Comment by svpernova09** [comment]
> Wow, many thanks. I missed it somehow

I've been *very* quiet on it :)


You should be able to destroy your laravel/homestead VM, copy your `Homestead.yaml` into the forked repo, and spin up a fresh instance from there. If not please come back and open an issue and let me know what went wrong.
